import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/">Home</Link>
        <Link href="/blog">Blog</Link>
        {children}
      </body>
    </html>
  );
}
